<a href="https://colab.research.google.com/github/gaurpranjal617-web/DSV-Lab/blob/main/Practice_Sheet_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

sales = pd.Series([120, 150, 180, 210])

print(sales)

0    120
1    150
2    180
3    210
dtype: int64

In [ ]:
marks = pd.series([72, 81, 69, 90])
marks.values

array([72,81,69,90])

In [ ]:
import pandas as pd
marks = pd.Series([72,81,69,90])
marks.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
temperatures = pd.Series([28,31,30,29], index=["Mon","Tues","Wed","Thu"])
print(temperatures)

Mon     28
Tues    31
Wed     30
Thu     29
dtype: int64

In [ ]:
population = pd.Series([35,42,31], index=['Delhi','Mumbai','Jaipur'])
int(population['Jaipur'])

31

In [ ]:
score = pd.Series([35,68,44,79,52])
result = score[score > 50]
result

1    68
3    79
4    52
dtype: int64

In [ ]:
subjects = pd.Series([76,83,91], index=['Physics','Chemistry','Maths'])
'Chemistry' in subjects.index

True

In [ ]:
marks = pd.Series([72,81,69], index=['Maths', 'Science', 'English'])
dictionary = marks.to_dict()
dictionary

{'Maths': 72, 'Science': 81, 'English': 69}

In [ ]:
prices = {'Pen': 10, 'Notebook': 55, 'Bag': 700}
price_series = pd.Series(prices)
price_series

Pen          10
Notebook     55
Bag         700
dtype: int64

In [ ]:
data = {'A' : 10, 'B' : 20, 'C' : 30}
s = pd.Series(data, index=['A','B','C','D'])
s

A    10.0
B    20.0
C    30.0
D     NaN
dtype: float64

In [ ]:
s = pd.Series([10,20,None,40])
s.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
s = pd.Series([10,20,None,40])
s.notnull()

0     True
1     True
2    False
3     True
dtype: bool

In [ ]:
sales = pd.Series([120,150,180,210])
sales.name = "Monthly sales"
sales

0    120
1    150
2    180
3    210
Name: Monthly sales, dtype: int64

In [ ]:
sales = pd.Series([120,150,180,210], index=['Jan','Feb','Mar','Apr'])
sales.index.name = "Month"
sales

Month
Jan    120
Feb    150
Mar    180
Apr    210
dtype: int64

In [ ]:
s = pd.Series([500,600,700], index=['East', 'West', 'North'])
'West' in s
500 in s

False

In [ ]:
city_data = {'Delhi': 80, 'Pune': 65, 'Kochi': 70}
city_series = pd.Series(city_data, index=['Delhi', 'Pune', 'Mumbai', 'Kochi'])
city_series

Delhi     80.0
Pune      65.0
Mumbai     NaN
Kochi     70.0
dtype: float64

In [ ]:
s = pd.Series({'W': 5, 'X': 10, 'Y': 15}, index=['W','X', 'Y', 'Z'])
pd.isnull(s)

W    False
X    False
Y    False
Z     True
dtype: bool

In [ ]:
s = pd.Series({'W': 5, 'X' : 10, 'Y' : 15}, index=['W','X', 'Y', 'Z'])
pd.notnull(s)

W     True
X     True
Y     True
Z    False
dtype: bool